### ISSUE TITLE
Created & Description field data

### ISSUE THREAD

**Issue by mfielderUS** [notoriousbdg/vrops-dashboard-snapshot_detail#3]
I've made the edits to the Policy as directed, making them both Local Enabled, in an area of the Policy library that would cover all objects. My issue is that for both columns I'm only seeing entries on VMs I created, There are hundreds of other VMs with snapshots in the view and they are all blank.

 Looking at view in design, both data objects metric name begins with **"Disk Space:2865|Snapshot:snapshot-1|....".** I don't find the number "**2865**" after any metrics in the, could you explain it's source?

Running vROps 7.0 from upgrade of 6.7.  Changes made at a point in Policy Library that I know it is applied to all objects.

**Comment by notoriousbdg** [comment]
Are all the fields in the rows blank or just created and description?  Perhaps a screenshot would help?

"2865" is the instance ID of the datastore.  In your environment, look for the datastore name at that spot instead.  Note that created and description are properties, so you'll need to look for them under All Properties instead of All Metrics.

**Comment by amar9057** [comment]
Hey,
Good Day to all!!

I am also facing the same issue. Only creator and description columns fields are blank rest all are good.

What was the resolution adopted if this is solved. Please respond asap.

Thanks

Amar pal Singh
