### ISSUE TITLE
Snapshot Age

### ISSUE THREAD

**Issue by jturnya** [notoriousbdg/vrops-dashboard-snapshot_detail#4]
Do you know why the report would grab snapshots that are aged -1 days? Or some time I will get 0 days or 1 day snapshots. I have a filter set to only report on snapshots older than 2 days. However, on some of the VMs in the report, I will get multiple snapshots with different ages, but there really is only 1 snapshot in snapshot manager. Also, if I drill down into the datastore, I can only find small delta files that could possibly resemble that date.

**Comment by notoriousbdg** [comment]
There are a couple of things that can cause that.  Performing an svmotion of a VM with a snapshot can create extra snapshot instances.  Also, a VM that has had more than one snapshot in the past and currently has at least 1 active snapshot and less than that number of active snapshots now.  Unfortunately, there is no way to filter those out because filters don't work on instanced metrics.  Deleting all snapshots on the VM should remove them from the list, but if there is at least 1 snapshot, it's possible to see some extra ones with -1 age.

**Comment by notoriousbdg** [comment]
This issue has been addressed with vROps 8.2 and the latest version of this dashboard.  Please upgrade to vROps 8.2 and update to the latest version of this dashboard.
